title: Janet's Finance Blog
description: Deep dives into finance, tools, and data
baseurl: "" # Leave empty if using root GitHub Pages
url: "https://janetbaby.github.io"

theme: minima

header_pages:
  - index.md
  - about.md

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
